pipeline{
    agent any
    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/agustinsaavedra2/PEP1_Tingeso']])
                dir("PEP1_Tingeso_Frontend"){
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                dir("PEP1_Tingeso_Frontend"){
                    script{
                         withDockerRegistry(credentialsId: 'docker-credentials'){
                            bat "docker build -t agustinsaavedra056/pep1_tingeso_frontend:latest ."
                            bat "docker push agustinsaavedra056/pep1_tingeso_frontend:latest"
                        }
                    }                    
                }
            }
        }
    }
}