version: "3.8"

services: 
    backend1:
      image: agustinsaavedra056/pep1_tingeso_backend:latest
      environment:
        - DB_HOST=192.168.100.129
        - DB_PASSWORD=laucesbkn2001
      networks: 
        - backend-network

    backend2:
      image: agustinsaavedra056/pep1_tingeso_backend:latest
      environment:
        - DB_HOST=192.168.100.129
        - DB_PASSWORD=laucesbkn2001
      networks: 
        - backend-network
    
    backend3:
      image: agustinsaavedra056/pep1_tingeso_backend:latest
      environment:
        - DB_HOST=192.168.100.129
        - DB_PASSWORD=laucesbkn2001
      networks: 
        - backend-network
    
    frontend1:
      image: agustinsaavedra056/pep1_tingeso_frontend:latest
      networks: 
        - frontend-network
    frontend2:
      image: agustinsaavedra056/pep1_tingeso_frontend:latest
      networks: 
        - frontend-network
    frontend3:
      image: agustinsaavedra056/pep1_tingeso_frontend:latest
      networks: 
        - frontend-network
    backend-nginx:
      image: nginx:latest
      ports: 
        - "8080:8080"
      volumes:
        - ./backend.conf:/etc/nginx/nginx.conf
      depends_on:
        - backend1
        - backend2
        - backend3
      networks: 
        - backend-network
    frontend-nginx:
      image: nginx:latest
      ports:
        - "5173:80"
      volumes: 
        - ./frontend.conf:/etc/nginx/nginx.conf 
      depends_on:
        - frontend1
        - frontend2
        - frontend3
      networks:
        - frontend-network

networks:
  backend-network:
  frontend-network: